# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'iweather' do
    pod 'RealmSwift'
    pod 'Alamofire'
    pod 'SwiftGifOrigin', '~> 1.6.1'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
#    pod 'Reusable'
end

target 'myWeather' do
    pod 'RealmSwift'
    pod 'Alamofire'
    pod 'SwiftGifOrigin', '~> 1.6.1'
end
